version: '3.9'

services:
  auth_db:
    image: postgres:latest
    container_name: auth_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_pass
    volumes:
      - auth_db_data:/var/lib/postgresql/data


      - post_db_data:/var/lib/postgresql/data

  comment_db:
    image: postgres:latest
    container_name: comment_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=comment_db
      - POSTGRES_USER=comment_user
      - POSTGRES_PASSWORD=comment_pass
    volumes:
      - comment_db_data:/var/lib/postgresql/data

  auth_service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - auth_db

  post_service:
    build:
      context: ./post-service
      dockerfile: Dockerfile
    image: simplified-blog-post_service
    container_name: post-service_con
    environment:
      url: jdbc:postgresql://post_db:5432/post_db
      username: post_user
      password: post_pass
    ports:
      - "8089:8080"
    depends_on:
      - post_db
    restart: always

  comment_service:
    build:
      context: ./comment-service
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      - comment_db

volumes:
  auth_db_data:
  comment_db_data:
  post_db_data: