version: '3.9'

services:
  post_db:
    image: postgres:latest
    container_name: post_db
    environment:
      POSTGRES_DB: post_db
      POSTGRES_USER: post_user
      POSTGRES_PASSWORD: post_pass
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - 5433:5432
    volumes:
      - /var/lib/postgresql/data
  adminer:
      image: adminer
      restart: always
      ports:
        - 8090:8080

  post_service:
    build:
      context: ./post-service
      dockerfile: Dockerfile
    ports:
      - "8082:8000"
    depends_on:
      - post_db

