#Server Port configuration
server:
  port: 8080

#Postgres configuration
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:post_db
    username: post_user
    password: post_pass

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

#Configure Swagger
#springdoc:
#  swagger-ui:
#    disable-swagger-default-url: true
#    path: /
